### ISSUE TITLE
While the game is paused, object placements are not drawn.

### ISSUE THREAD

**Issue by Vorgon1** [CompletelyFairGames/dwarfcorp#218]
Just found this game looking for stuff on Dwarf Fortress and trying it out. Dug out a room for beds, but when selecting the location, it's just a white wireframe box and a tool tip for rotation. Ended up building several beds overlapping because I didn't know they were 2 blocks long. Same thing with building a wood door. Just a wire frame block. Hasn't been built yet, so don't know which way it will be turned.

**Comment by mklingen** [comment]
Interesting, this should have been fixed already. Will test again. Can I ask which platform/build you were running?

**Comment by Vorgon1** [comment]
Win7 XNA version downloaded last night (the 4th). Couldn't a version number in game or a version file. didn't check every folder though. :)

**Comment by mklingen** [comment]
I'm very sorry but I can't seem to reproduce this bug. I will keep an eye on it.

**Comment by Vorgon1** [comment]
I was just playing a new game and put down several beds and other items (stove, cooking table, etc.) and none of them showed during placement. Just the white wireframe box. When moving the beds after construction, you do still see the item during placement.

**Comment by Vorgon1** [comment]
Figured it out. I always like to setup orders while paused so I can think about it without something interrupting or getting missed. In Pause you only get the box frame. But when placing out of pause, objects apear. Pause is pausing the drawing of object build planning. It doesn't seem to effect placing blocks.

**Comment by mklingen** [comment]
> all the fence sections are turned the same way until after restart. Animals are too buggy to use now anyway. Giving orders to wrangle gives the error not enough pens and after 2 or 3 tries the game crashes.

This has just been fixed and will be in the next build.

> Figured it out. I always like to setup orders while paused so I can think about it without something interrupting or getting missed. I

Nice catch! I will put in a fix for this soon. A lot of things don't draw correctly when the game is paused.

**Comment by mklingen** [comment]
Issue fixed by this commit on my branch: https://github.com/CompletelyFairGames/dwarfcorp/commit/a153d0f0f0bd0ba6c2f0abbb01eeff77d345b6c9

Fix will be in the next build.
