### ISSUE TITLE
[BUG] Game Won't Launch (Fedora 27)

### ISSUE THREAD

**Issue by koenigjaeger** [CompletelyFairGames/dwarfcorp#502]
**Specs:**
Fedora 27 [kernel: 4.14.3-300.fc27.x86_64]
Running under Wayland display server and Xorg
Game Version: 17.12.04
With the following hardware...
Ryzen 5 1600
RX 580 [AMD Polaris10 / drm 3.19.0 / 4.14.3-300.fc27.x86_64, llvm 4.0.1/ 3.0 Mesa 17.2.4]
&
XPS13 (9343)

When launching from steam the game won't start. Steam will say "Running" and then stop. When starting the game from the terminal the follow output is received.
[dwarf_corp_error.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1561712/dwarf_corp_error.txt)

**Comment by Iamledgen** [comment]
Same Issue, starting to notice Ive waisted 20$ on a game that I cant even open.

**Comment by koenigjaeger** [comment]
@Iamledgen It was working on 17.11.19 at least. So it is possible it's an issue with the libraries provided by steam, or just an error on their part that can be reverted. They are normally very responsive and quick to fix issues.You are using Fedora 27 as well?

**Comment by Iamledgen** [comment]
Actually I am not, i seem to have posted in the wrong area. I using just base MAC OS X.

**Comment by koenigjaeger** [comment]
I also launched steam through the terminal and then launched to game and got the following output (I tried to find the info for when Dwarfcorp started).
[dwarf_corp_error_v2.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1564493/dwarf_corp_error_v2.txt)

If there is any crash logs that the game auto generates let me know and I can upload those. 

@Iamledgen  No problem. You can try and start the game from the terminal and see if the game reports any missing libraries or (this may be more useful) start steam from the terminal and then start the game and see what the terminal outputs. I don't know if the game auto generates crash logs that you can just look at.

**Comment by Iamledgen** [comment]
this is going to be long I apologize but this is what came up as a result
 [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not find file [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not find file "/Users/kimberlybuehler/Library/Application Support/Steam/steamapps/common/DwarfCorp/DwarfCorp.app/Contents/MacOS/.\Content\newgui\sheets.txt".
File name: '/Users/me/Library/Application Support/Steam/steamapps/common/DwarfCorp/DwarfCorp.app/Contents/MacOS/.\Content\newgui\sheets.txt'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0021a] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) [0x00000] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) [0x00079] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) [0x00000] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) [0x0000d] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.IO.StreamReader..ctor (System.String path) [0x00000] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader:.ctor (string)
  at System.IO.File.ReadAllText (System.String path) [0x00000] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at DwarfCorp.Gui.RenderData..ctor (Microsoft.Xna.Framework.Graphics.GraphicsDevice Device, Microsoft.Xna.Framework.Content.ContentManager Content, System.String Effect, System.String Skin) [0x00032] in <5d1065f6aae147cf81e268cf6a6e2638>:0 
  at DwarfCorp.DwarfGame.LoadContent () [0x00040] in <5d1065f6aae147cf81e268cf6a6e2638>:0

**Comment by koenigjaeger** [comment]
@Iamledgen Try and just copy it into a text editor and save it as a *.txt and then upload the file to github (you should just be able to drag and drop). I would recommend that you open a new issue, since this thread deals with Linux less people are going to be able to see it who use OSX/Mac. So just state what OS you are using, the hardware, the version of the game and then upload your *.txt file and state the issue you are having. Also include [OS version] in the title, just so other users can find relevant issues.

**Comment by mklingen** [comment]
Hmm, I'm sorry about that. We made a change to the linux launch script which must have broken things. https://github.com/CompletelyFairGames/dwarfcorp/commit/2f4e2fdbb572cbf125627444c19873e069199c15

That change was intended to allow use of the system-wide SDL instead of the one we included. Will try to reproduce on ubuntu today.

**Comment by mklingen** [comment]
Seems to be the same problem as this:
https://bugzilla.redhat.com/show_bug.cgi?id=1496895

If so we can try to update the SDL included in our linux build.

**Comment by mklingen** [comment]
FYI, there are apparently multiple issues on Linux and Mac since last week. Going through them now.

**Comment by mklingen** [comment]
Steps I've taken to possibly fix this

1) really ensure that LibSDL can come from user installation if possible.
2) fix some file paths we added that had inlined "\\" as a file seperator rather than using the system seperator.
3) upgrade the version of SDL that we distribute

**Comment by Iamledgen** [comment]
Do you know when exactly you will have the "hotfix" uploaded to steam ive deleted my request for refund in hopes youll fix the issue soon

**Comment by mklingen** [comment]
likely tomorrow night, thank you for your patience

**Comment by koenigjaeger** [comment]
@mklingen Tested version 17.12.17 on the specs in the OP and still crashing. I can get to the main screen on the XPS13 but then it crashes ~3 seconds later and on the ryzen based system I don't even see the title screen. I reinstalled the game with the same results. I don't have any logs to share right now, but I'll try to get some tomorrow.

**Comment by mklingen** [comment]
Crap sorry. Will have to keep the issue open then. Wasn't this game working for you before?

**Comment by koenigjaeger** [comment]
Yeah, it was. I believe it was working on version 17.11.19 last. I'll try to get some logs soon. Was it working for you on a Fedora machine? or just Ubuntu?

**Comment by mklingen** [comment]
I have only tested on Ubuntu, but it's very interesting that it was working for you in 17.11.19. I don't think I've changed anything which chould have caused this issue on Fedora since then.  If it's still reporting the DBUS error, it's an instance of this failure: https://bugzilla.redhat.com/show_bug.cgi?id=1496895 which is apparently fixed by upgrading SDL.

**Comment by mklingen** [comment]
possibly related to #520 , fix was to export LD_LIBRARY_PATH to the install directory.

**Comment by koenigjaeger** [comment]
@mklingen So it's been a while since I posted/ updated. The lasted release (18.02.25 with hot fix) still experiences the same issues as before. Although this time I cam get to the loading screen on the Ryzen based system, however if crashes right after. I ran steam through the terminal and then launched dwarf corp and got the following errors which I've
[dwarf_error.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1769088/dwarf_error.txt)
 attached.

**Comment by koenigjaeger** [comment]
Seems to be related to #513

**Comment by koenigjaeger** [comment]
Just tried what those in #513 and #520 recommended and disabling the steam overlay (/Steam/Settings/In Game) worked. The game now launches without issue.

**Comment by mklingen** [comment]
Interesting information. Thanks for looking into this. I'm going to bring this crash up with Valve and see if they know what might be going on (after all, the Steam Overlay just gets injected into our binary without us asking).

**Comment by com1clyf3** [comment]
Sounds like this is resolved. Closing for regression. Valve ever get back to you @mklingen ?
